package com.riverfishing.registry;

import com.google.common.collect.ImmutableSet;
import com.riverfishing.RiverFishing;
import com.riverfishing.item.FishItem;
import it.unimi.dsi.fastutil.ints.Int2ObjectMap;
import it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap;
import net.minecraft.core.Holder;
import net.minecraft.core.Registry;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceKey;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.tags.TagKey;
import net.minecraft.util.RandomSource;
import net.minecraft.util.Unit;
import net.minecraft.world.entity.ai.village.poi.PoiType;
import net.minecraft.world.entity.npc.villager.Villager;
import net.minecraft.world.entity.npc.villager.VillagerData;
import net.minecraft.world.entity.npc.villager.VillagerProfession;
import net.minecraft.world.item.trading.MerchantOffer;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.trading.MerchantOffers;
import net.minecraft.world.item.trading.TradeSet;
import net.minecraft.world.item.trading.VillagerTrade;
import net.minecraft.world.level.storage.loot.LootContext;
import net.minecraft.world.level.storage.loot.LootParams;
import net.minecraft.world.level.storage.loot.parameters.LootContextParamSets;
import net.minecraft.world.level.storage.loot.parameters.LootContextParams;
import dev.architectury.registry.registries.DeferredRegister;
import dev.architectury.registry.registries.RegistrySupplier;
import net.minecraft.core.registries.Registries;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.Set;

/**
 * Fisherman villager (§8): a custom profession with its own POI job-site block ("Fishing Stall") and
 * five trade tiers. §26.1: trades are DATA-DRIVEN now — the profession record itself points at our
 * trade_set JSONs (data/riverfishing/trade_set/fisherman/level_N.json, generated by
 * tools/gen_villager_trades.py from the same table the old Java builders encoded), so the whole
 * runtime trade-registration seam (VillagerTradesEvent / TradeOfferHelper) is gone.
 *
 * <p><b>§trade-pool</b> lives entirely in that data now. Vanilla draws {@code amount} offers per level
 * out of the level's tag without replacement, so pool size is the currency; the old {@code oneOf}
 * rotating listing is emulated with a {@code merchant_predicate} weight (a declined trade is re-rolled),
 * which lands the effective pools back on 10/10/7/14/12 with two fish-buy slots each. Three offers per
 * level is just {@code "amount": 3}. See the generator's header for the whole argument.
 *
 * <p>The ONE thing data cannot express is the level-1 guarantee — see {@link #ensureStarterFish}.
 */
public final class ModVillagers {
    public static final DeferredRegister<PoiType> POI_TYPES =
            DeferredRegister.create(RiverFishing.MODID, Registries.POINT_OF_INTEREST_TYPE);
    public static final DeferredRegister<VillagerProfession> PROFESSIONS =
            DeferredRegister.create(RiverFishing.MODID, Registries.VILLAGER_PROFESSION);

    public static void init() {
        POI_TYPES.register();
        PROFESSIONS.register();
    }

    public static final RegistrySupplier<PoiType> FISHERMAN_POI = POI_TYPES.register("fisherman",
            () -> new PoiType(Set.copyOf(ModBlocks.FISHING_STALL.get().getStateDefinition().getPossibleStates()), 1, 1));

    /** Level → our trade_set datapack entry (fisherman/level_1 … fisherman/level_5). */
    private static Int2ObjectMap<ResourceKey<TradeSet>> tradeSets() {
        Int2ObjectMap<ResourceKey<TradeSet>> m = new Int2ObjectOpenHashMap<>();
        for (int lvl = 1; lvl <= 5; lvl++) {
            m.put(lvl, ResourceKey.create(Registries.TRADE_SET, RiverFishing.id("fisherman/level_" + lvl)));
        }
        return m;
    }

    public static final RegistrySupplier<VillagerProfession> FISHERMAN = PROFESSIONS.register("fisherman",
            () -> new VillagerProfession(
                    Component.translatable("entity.minecraft.villager.riverfishing.fisherman"),
                    holder -> holder.is(FISHERMAN_POI.getKey()),
                    holder -> holder.is(FISHERMAN_POI.getKey()),
                    ImmutableSet.of(), ImmutableSet.of(),
                    SoundEvents.VILLAGER_WORK_FISHERMAN,
                    tradeSets()));

    /**
     * §order-tier: which fisherman level buys each species. The order-of-the-day board prints it — the
     * standing complaint that an order can name a fish the player's own fisherman will not take is, at
     * bottom, that the requirement was never stated anywhere.
     *
     * <p>§26.1: the trades are data, so the answer is READ OUT of the generated datapack rather than
     * recorded while Java builders run — {@code fisherman/<level>/buy_<species>} is the id
     * {@code gen_villager_trades.py} writes for every fish buy, so this cannot drift from the pools.
     *
     * @return the lowest fisherman level that buys this species, or 0 if none does (also off-world).
     */
    public static int buyTier(String species) {
        // §26.x: ResourceKey.location() is identifier() here — the same rename that turned
        // ResourceLocation into Identifier, and the compiler is the one that found it.
        return buyTrade(species)
                .map(h -> Integer.parseInt(h.key().identifier().getPath().split("/")[1]))
                .orElse(0);
    }

    /**
     * The generated buy trade for a species — the ONE place that knows the id shape
     * {@code fisherman/<level>/buy_<species>} the generator writes. {@link #buyTier} and
     * {@link #basePrice} are two questions with one answer, so they cannot disagree; the level is
     * read back off the key rather than handed out through a field, because a second return value
     * smuggled through static state is how two answers get out of step in the first place.
     */
    private static Optional<Holder.Reference<VillagerTrade>> buyTrade(String species) {
        net.minecraft.server.MinecraftServer server = dev.architectury.utils.GameInstance.getServer();
        if (server == null) return Optional.empty();
        Registry<VillagerTrade> trades = server.registryAccess().lookupOrThrow(Registries.VILLAGER_TRADE);
        for (int lvl = 1; lvl <= 5; lvl++) {
            var found = trades.get(RiverFishing.id("fisherman/" + lvl + "/buy_" + species));
            if (found.isPresent()) return found;
        }
        return Optional.empty();
    }

    /**
     * §order-slot: every species some fisherman buys, sorted, so the daily rotation cannot name a fish
     * nobody takes. Read out of the trade registry — the trades ARE the answer, so there is no second
     * list to drift. Cached because it can only change with the datapack.
     */
    private static java.util.List<String> buyable = java.util.List.of();

    public static java.util.List<String> buyableSpecies() {
        if (!buyable.isEmpty()) return buyable;
        net.minecraft.server.MinecraftServer server = dev.architectury.utils.GameInstance.getServer();
        if (server == null) return java.util.List.of();
        Registry<VillagerTrade> trades = server.registryAccess().lookupOrThrow(Registries.VILLAGER_TRADE);
        java.util.TreeSet<String> found = new java.util.TreeSet<>();
        for (var key : trades.registryKeySet()) {
            String path = key.identifier().getPath();
            int cut = path.indexOf("/buy_");
            if (path.startsWith("fisherman/") && cut > 0) found.add(path.substring(cut + 5));
        }
        buyable = java.util.List.copyOf(found);
        return buyable;
    }

    /**
     * §order-slot: one seat on this counter always shows today's order.
     *
     * <p>It REPLACES rather than appends, and that is the whole design. An extra offer would have to be
     * found and reclaimed the next day, and there is nothing on a vanilla MerchantOffer to mark it with
     * that survives a save — so every scheme for finding it again came down to counting the counter,
     * which breaks the moment a villager gains a level and vanilla appends behind our seat. Overwriting
     * a seat in place has none of that: the counter never changes size, so there is nothing to count,
     * nothing to mark, and nothing to get wrong after a restart.
     *
     * <p>The seat is the last fish buy on the counter. On the first day that costs one drawn species,
     * and from then on it is the same seat every day — which is what makes it a permanent slot that
     * changes rather than a new trade appearing and disappearing.
     *
     * <p>Nothing happens when the stall is too junior to buy today's species, or when it already buys
     * it: in the second case the player can sell it anyway, and taking the seat would only cost them a
     * second species for nothing.
     */
    private static void orderSlot(Villager villager, ServerLevel level, MerchantOffers offers) {
        String order = com.riverfishing.fishing.MarketData.orderOfTheDay(level);
        int tier = buyTier(order);
        if (tier <= 0 || tier > villager.getVillagerData().level()) return;
        int seat = -1;
        for (int i = 0; i < offers.size(); i++) {
            if (!(offers.get(i).getCostA().getItem() instanceof FishItem fish)) continue;
            if (fish.species().getPath().equals(order)) return;   // already on the counter
            seat = i;
        }
        if (seat < 0) return;
        MerchantOffer offer = offerFor(villager, level, order);
        if (offer != null) offers.set(seat, offer);
    }

    /** One buy offer for a species, rolled through the same loot context vanilla uses for trades. */
    private static MerchantOffer offerFor(Villager villager, ServerLevel level, String species) {
        var trade = buyTrade(species);
        if (trade.isEmpty()) return null;
        LootContext context = new LootContext.Builder(new LootParams.Builder(level)
                .withParameter(LootContextParams.ORIGIN, villager.position())
                .withParameter(LootContextParams.THIS_ENTITY, villager)
                .withParameter(LootContextParams.ADDITIONAL_COST_COMPONENT_ALLOWED, Unit.INSTANCE)
                .create(LootContextParamSets.VILLAGER_TRADE)).create(Optional.empty());
        return trade.get().value().getOffer(context);
    }

    /** §market-live: the emeralds the datapack pays for this species before the market moves it. */
    private static int basePrice(String species) {
        return buyTrade(species)
                .map(h -> ((com.riverfishing.mixin.VillagerTradeGivesAccessor) (Object) h.value())
                        .riverfishing$gives().count())
                .orElse(0);
    }

    /**
     * §market-live: re-price this stall's fish buys from the base, every time the counter opens.
     *
     * <p>The base is read from where the trade was DEFINED, never from the offer's current count —
     * feeding the output back in would multiply ×2.5 on top of ×2.5 every time the player looked.
     */
    public static void repriceFishBuys(Villager villager) {
        if (!(villager.level() instanceof ServerLevel level)) return;
        if (!villager.getVillagerData().profession().is(FISHERMAN.getKey())) return;
        MerchantOffers offers = villager.getOffers();
        orderSlot(villager, level, offers);
        var market = com.riverfishing.fishing.MarketData.get(level);
        for (MerchantOffer offer : offers) {
            if (!(offer.getCostA().getItem() instanceof FishItem fish)) continue;
            String species = fish.species().getPath();
            int base = basePrice(species);
            if (base <= 0) continue;
            ItemStack pay = offer.getResult();
            // A stack is the ceiling: blue marlin at ×2.5 is 70 emeralds, which will not fit in a slot.
            pay.setCount(Math.min(pay.getMaxStackSize(), market.price(level, species, base)));
        }
    }

    /** Prime-grade threshold (§prime-fish): the buyer only takes the top of the species' size range. */
    public static final double PRIME_FRACTION = 0.7;

    /**
     * §starter-fish: the unweighted fish buys a level-1 stall falls back on. The species live in the
     * datapack tag (generated alongside the pools), so this class only needs to know the tag id — and
     * these trades are in NO level pool, so they carry no {@code merchant_predicate} weight and always
     * yield an offer.
     */
    private static final TagKey<VillagerTrade> STARTER_FISH =
            TagKey.create(Registries.VILLAGER_TRADE, RiverFishing.id("fisherman/starter"));

    private ModVillagers() {}

    /**
     * §starter-fish: called from {@link com.riverfishing.mixin.VillagerTradePoolMixin} the moment vanilla
     * has filled a freshly unlocked level. A level-1 draw is pure chance, so a fresh stall could come up
     * gear-only — and that first emerald for a bleak is the whole point of the profession, so one fish buy
     * is swapped in rather than appended (the counter still shows exactly the drawn number of offers).
     *
     * <p>Every villager runs this hook; anyone who isn't our fisherman on level 1 returns immediately.
     */
    public static void ensureStarterFish(Villager villager, ServerLevel level) {
        VillagerData data = villager.getVillagerData();
        if (data.level() != 1 || !data.profession().is(FISHERMAN.getKey())) return;

        MerchantOffers offers = villager.getOffers();
        int replace = -1;
        for (int i = 0; i < offers.size(); i++) {
            if (offers.get(i).getCostA().getItem() instanceof FishItem) return;   // already buys fish
            replace = i;                                                          // last non-fish offer
        }
        if (replace < 0) return;

        MerchantOffer fish = starterOffer(villager, level);
        if (fish != null) offers.set(replace, fish);
    }

    /** Rolls one of the tagged starter buys through the same loot context vanilla uses for trades. */
    private static MerchantOffer starterOffer(Villager villager, ServerLevel level) {
        Registry<VillagerTrade> registry = level.registryAccess().lookupOrThrow(Registries.VILLAGER_TRADE);
        List<Holder<VillagerTrade>> candidates = new ArrayList<>();
        registry.getTagOrEmpty(STARTER_FISH).forEach(candidates::add);
        if (candidates.isEmpty()) return null;

        LootContext context = new LootContext.Builder(new LootParams.Builder(level)
                .withParameter(LootContextParams.ORIGIN, villager.position())
                .withParameter(LootContextParams.THIS_ENTITY, villager)
                .withParameter(LootContextParams.ADDITIONAL_COST_COMPONENT_ALLOWED, Unit.INSTANCE)
                .create(LootContextParamSets.VILLAGER_TRADE)).create(Optional.empty());

        // Walk from a random start rather than shuffling a copy: same fairness, no allocation, and it
        // stops at the first species whose item actually registered.
        RandomSource random = villager.getRandom();
        int start = random.nextInt(candidates.size());
        for (int i = 0; i < candidates.size(); i++) {
            MerchantOffer offer = candidates.get((start + i) % candidates.size()).value().getOffer(context);
            if (offer != null) return offer;
        }
        return null;
    }
}
