package com.riverfishing.item;

import com.riverfishing.RiverFishing;
import com.riverfishing.component.ComponentSlot;
import com.riverfishing.component.RigType;
import com.riverfishing.component.RodType;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.core.registries.BuiltInRegistries;

/**
 * Reads/writes the reel, line, rig and hook stored inside an assembled rod's NBT (§3.1, §12).
 * The rod item itself carries the {@link com.riverfishing.component.RodType}.
 */
public final class RodData {
    public static final String ROOT = "RodComponents";

    private RodData() {}

    private static String key(ComponentSlot slot) {
        return switch (slot) {
            case REEL -> "Reel";
            case LINE -> "Line";
            case RIG -> "Rig";
            case HOOK -> "Hook";
        };
    }

    public static ItemStack get(ItemStack rod, ComponentSlot slot) {
        CompoundTag tag = StackNbt.get(rod);
        if (!tag.contains(ROOT)) return ItemStack.EMPTY;
        CompoundTag root = tag.getCompoundOrEmpty(ROOT);
        String k = key(slot);
        if (!root.contains(k)) return ItemStack.EMPTY;
        return com.riverfishing.util.RegistryHelper.loadStack(root.getCompoundOrEmpty(k));
    }

    public static void set(ItemStack rod, ComponentSlot slot, ItemStack component) {
        StackNbt.mutate(rod, tag -> {
            CompoundTag root = tag.getCompoundOrEmpty(ROOT);
            String k = key(slot);
            if (component.isEmpty()) {
                root.remove(k);
            } else {
                root.put(k, com.riverfishing.util.RegistryHelper.saveStack(component));
            }
            tag.put(ROOT, root);
        });
        refreshIconLayers(rod);
    }

    /**
     * §26.1 §rod-layers: the composited rod icon is data-driven now — the client item definition
     * SELECTs overlay layers on custom_model_data STRINGS (0 = reel sprite, 1 = line type,
     * 2 = rig sprite). Kept in sync here on every component change (26.1 has no item-model
     * condition that can look inside custom_data).
     */
    public static void refreshIconLayers(ItemStack rod) {
        String reel = "", line = "", rig = "";
        if (get(rod, ComponentSlot.REEL).getItem() instanceof ReelItem ri) {
            reel = "reel_" + ri.size();
        }
        if (get(rod, ComponentSlot.LINE).getItem() instanceof LineItem li) {
            line = li.lineType().jsonKey();
        }
        if (get(rod, ComponentSlot.RIG).getItem() instanceof RigItem gi) {
            rig = rigSprite(gi.rigType());
        }
        writeIcon(rod, getBend(rod), lineOut(rod), java.util.List.of(reel, line, rig));
    }

    /**
     * §rod-layers: FLAG 0 = the line is cast/out — the in-hand icon hides the line+rig overlays then
     * (the 3D line + bobber represents them, exactly like the old BEWLR did). Set by FishingManager
     * on cast, cleared when the session ends.
     */
    public static void setLineOut(ItemStack rod, boolean out) {
        writeIcon(rod, getBend(rod), out, strings(rod));
    }

    // ---- §rod-bend ----

    /** Bend steps; sprites are {@code blank_<rod>_bend1..N}, generated by {@code tools/GenRodBend.java}. */
    public static final int BEND_BUCKETS = 6;

    /**
     * §rod-bend: the bucket a 0..1 fight stress maps to (0 = straight blank). Same curve the 1.21.1
     * BEWLR used — a 6% dead zone so an idle line doesn't twitch the blank, then linear to full.
     */
    public static int bendBucket(float stress) {
        return stress <= 0.06f ? 0 : net.minecraft.util.Mth.clamp(
                (int) Math.ceil((stress - 0.06f) / 0.94f * BEND_BUCKETS), 1, BEND_BUCKETS);
    }

    /** §rod-bend: the bucket currently stored on the rod (FLOAT 0), 0 when straight. */
    public static int getBend(ItemStack rod) {
        var cmd = rod.get(net.minecraft.core.component.DataComponents.CUSTOM_MODEL_DATA);
        return cmd == null || cmd.floats().isEmpty() ? 0 : Math.round(cmd.floats().get(0));
    }

    /**
     * §rod-bend: FLOAT 0 = the bend bucket the item definition {@code range_dispatch}es the blank
     * layer on. Written SERVER-side by the fight, so every tracking player sees the blank load up —
     * not just the angler, which is all the 1.21.1 client-side BEWLR could manage.
     *
     * <p>Each write dirties the stack and re-broadcasts it to everyone tracking the angler, so this
     * is a no-op unless the bucket actually CHANGED. Empty rods are ignored: {@code ItemStack.EMPTY}
     * is a shared singleton and must never be mutated.
     */
    public static void setBend(ItemStack rod, int bucket) {
        if (rod.isEmpty() || getBend(rod) == bucket) return;
        writeIcon(rod, bucket, lineOut(rod), strings(rod));
    }

    /**
     * The one place the icon component is built — every setter here is a read-modify-write that has
     * to keep the OTHER lists intact. A straight rod stores no float at all, so a rod that never
     * fought carries exactly what it did before §rod-bend existed.
     */
    private static void writeIcon(ItemStack rod, int bend, boolean out, java.util.List<String> strings) {
        rod.set(net.minecraft.core.component.DataComponents.CUSTOM_MODEL_DATA,
                new net.minecraft.world.item.component.CustomModelData(
                        bend <= 0 ? java.util.List.<Float>of() : java.util.List.of((float) bend),
                        java.util.List.of(out), strings, java.util.List.of()));
    }

    private static java.util.List<String> strings(ItemStack rod) {
        var cmd = rod.get(net.minecraft.core.component.DataComponents.CUSTOM_MODEL_DATA);
        return cmd != null && cmd.strings().size() >= 3
                ? cmd.strings() : java.util.List.of("", "", "");
    }

    private static boolean lineOut(ItemStack rod) {
        var cmd = rod.get(net.minecraft.core.component.DataComponents.CUSTOM_MODEL_DATA);
        return cmd != null && !cmd.flags().isEmpty() && Boolean.TRUE.equals(cmd.flags().get(0));
    }

    /** Overlay sprite for a rig type — float_light/winter have no own glyph, nearest look-alike. */
    private static String rigSprite(RigType type) {
        return switch (type.jsonKey()) {
            case "float_light" -> "rig_float";
            case "winter" -> "rig_primitive";
            default -> "rig_" + type.jsonKey();
        };
    }

    /**
     * A rod can fish once it has a line and a rig (Module 4: hooks live inside the rig now, and an
     * empty hook only lowers the bite chance, it doesn't block casting).
     */
    public static boolean isAssembled(ItemStack rod) {
        return missingKey(rod) == null;
    }

    /**
     * Translation key naming the FIRST part the rod still needs, or null when it can fish
     * (§assembly-hint). A bare "the rod is not assembled" made players hunt blind — a reeled blank
     * REFUSES line until its reel is fitted, and a silently bouncing line slot reads as a broken GUI.
     */
    public static String missingKey(ItemStack rod) {
        // The reel check stands ON ITS OWN, not only when the line is missing: assembly is ordered
        // (reel before line), but disassembly is not — pulling the reel out from under a fitted line
        // used to slip past this and the rod cast with line spooled on nothing.
        if (rod.getItem() instanceof RodItem ri && ri.rodType().takesReel()
                && get(rod, ComponentSlot.REEL).isEmpty()) {
            return "message.riverfishing.need_reel";
        }
        if (get(rod, ComponentSlot.LINE).isEmpty()) return "message.riverfishing.need_line";
        if (get(rod, ComponentSlot.RIG).isEmpty()) return "message.riverfishing.need_rig";
        return null;
    }

    /** Float depth setting stored on the ROD ("спуск", §fishing-depth): surface / mid / bottom. */
    public static String getDepth(ItemStack rod) {
        String d = StackNbt.get(rod).getStringOr("SetDepth", "");
        return d.isEmpty() ? "mid" : d;
    }

    public static void setDepth(ItemStack rod, String depth) {
        StackNbt.mutate(rod, tag -> tag.putString("SetDepth", depth));
    }

    /**
     * Installs the rod's built-in rig into the RIG slot if it isn't already there (§closed-slots). Float
     * and lure rods own one native rig instead of a swappable one, so a freshly crafted or trade-bought
     * rod (or one whose rig was snapped off) gets it here. A rod that already holds the correct rig type
     * is left untouched, so its hooks/baits/leader survive. Rods with no native rig (bottom) are ignored.
     */
    public static void ensureNativeRig(ItemStack rod, RodType type) {
        RigType native_ = type.nativeRig();
        if (native_ == null) return;
        ItemStack rig = get(rod, ComponentSlot.RIG);
        if (rig.getItem() instanceof com.riverfishing.item.RigItem ri && ri.rigType() == native_) {
            return; // already the native rig — keep its contents
        }
        Item rigItem = BuiltInRegistries.ITEM.getValue(RiverFishing.id("rig_" + native_.jsonKey()));
        set(rod, ComponentSlot.RIG, rigItem != null ? new ItemStack(rigItem) : ItemStack.EMPTY);
    }
}
