"""Measure how much of its 256x256 canvas each fish sprite actually fills, and emit the table.

Why this exists: the keepnet draws a fish at the size of the cells it occupies, and the only way to do
that correctly is to know how big the fish is INSIDE its icon. A ray fills its canvas almost corner to
corner; an eel is a bar three pixels tall in the middle of it. Assuming one set of proportions for all of
them makes the ray right and the flounder tiny, which is exactly what happened.

Run after adding or redrawing a species:

    python tools/gen_fish_bounds.py

It writes common/src/main/java/com/riverfishing/client/FishBounds.java. Regenerating is idempotent.
"""
import io
import os
import struct
import zlib

TEX = 'common/src/main/resources/assets/riverfishing/textures/item/fish'
OUT = 'common/src/main/java/com/riverfishing/client/FishBounds.java'


def read_png(path):
    """Minimal PNG reader. The sprites here are a mix of RGBA and palette-with-tRNS, which is what a
    pixel-art tool writes when it can, so both are handled — and nothing else, loudly."""
    data = io.open(path, 'rb').read()
    assert data[:8] == b'\x89PNG\r\n\x1a\n', path
    pos, w, h, depth, ctype, idat, trns = 8, 0, 0, 0, 0, b'', b''
    while pos < len(data):
        ln = struct.unpack('>I', data[pos:pos + 4])[0]
        typ = data[pos + 4:pos + 8]
        body = data[pos + 8:pos + 8 + ln]
        if typ == b'IHDR':
            w, h, depth, ctype = struct.unpack('>IIBB', body[:10])
        elif typ == b'IDAT':
            idat += body
        elif typ == b'tRNS':
            trns = body
        pos += 12 + ln
    assert depth == 8 and ctype in (3, 6), f'{path}: unhandled PNG ({depth}/{ctype})'
    bpp = 4 if ctype == 6 else 1
    raw = zlib.decompress(idat)
    stride = w * bpp
    out = bytearray(h * stride)
    prev = bytearray(stride)
    p = 0
    for y in range(h):
        f = raw[p]
        p += 1
        line = bytearray(raw[p:p + stride])
        p += stride
        if f == 1:
            for i in range(bpp, stride):
                line[i] = (line[i] + line[i - bpp]) & 255
        elif f == 2:
            for i in range(stride):
                line[i] = (line[i] + prev[i]) & 255
        elif f == 3:
            for i in range(stride):
                a = line[i - bpp] if i >= bpp else 0
                line[i] = (line[i] + ((a + prev[i]) >> 1)) & 255
        elif f == 4:
            for i in range(stride):
                a = line[i - bpp] if i >= bpp else 0
                b = prev[i]
                c = prev[i - bpp] if i >= bpp else 0
                pp = a + b - c
                pa, pb, pc = abs(pp - a), abs(pp - b), abs(pp - c)
                pr = a if (pa <= pb and pa <= pc) else (b if pb <= pc else c)
                line[i] = (line[i] + pr) & 255
        out[y * stride:(y + 1) * stride] = line
        prev = line
    if ctype == 3:
        # A palette image keeps its alpha in tRNS, one byte per palette entry; anything past the end of
        # that chunk is opaque by definition.
        alpha = bytearray(w * h)
        for i, idx in enumerate(out):
            alpha[i] = trns[idx] if idx < len(trns) else 255
        return w, h, alpha, 1
    return w, h, out, 4


def bounds(path):
    """The alpha bounding box of the drawing, as fractions of the canvas."""
    w, h, px, ch = read_png(path)
    x0, y0, x1, y1 = w, h, -1, -1
    for y in range(h):
        row = y * w * ch
        for x in range(w):
            if px[row + x * ch + (3 if ch == 4 else 0)] > 8:
                if x < x0:
                    x0 = x
                if x > x1:
                    x1 = x
                if y < y0:
                    y0 = y
                if y > y1:
                    y1 = y
    if x1 < 0:
        return 1.0, 1.0
    return (x1 - x0 + 1) / w, (y1 - y0 + 1) / h


rows = []
for name in sorted(os.listdir(TEX)):
    if not name.endswith('.png'):
        continue
    fw, fh = bounds(os.path.join(TEX, name))
    rows.append((name[:-4], round(fw, 3), round(fh, 3)))

body = '\n'.join(f'        put("{n}", {w}f, {h}f);' for n, w, h in rows)
io.open(OUT, 'w', encoding='utf-8', newline='\n').write(f'''package com.riverfishing.client;

import java.util.HashMap;
import java.util.Map;

/**
 * §keepnet-bounds: how much of its own 256px icon each fish actually fills, across and down.
 *
 * <p>GENERATED by {{@code tools/gen_fish_bounds.py}} — do not hand-edit; redraw a sprite and re-run it.
 *
 * <p>The keepnet draws a fish at the size of the cells it occupies, and that is impossible to get right
 * without this: a ray fills its canvas almost corner to corner while an eel is a bar a few pixels tall in
 * the middle of one. Assuming a single set of proportions for all of them made the ray look right and the
 * flounder look tiny, which is the bug this table exists to kill.
 */
public final class FishBounds {{
    private static final Map<String, float[]> BOUNDS = new HashMap<>();

    private FishBounds() {{}}

    private static void put(String species, float w, float h) {{
        BOUNDS.put(species, new float[]{{w, h}});
    }}

    /** {{width, height}} as fractions of the icon, or the whole canvas for anything not a drawn fish. */
    public static float[] of(String species) {{
        return BOUNDS.getOrDefault(species, FULL);
    }}

    private static final float[] FULL = {{1f, 1f}};

    static {{
{body}
    }}
}}
''')
print(f'{len(rows)} sprites measured -> {OUT}')
for n, w, h in rows[:6]:
    print(f'  {n:14s} {w:.3f} x {h:.3f}')
