package com.riverfishing.client;

import java.util.HashMap;
import java.util.Map;

/**
 * §keepnet-bounds: how much of its own 256px icon each fish actually fills, across and down.
 *
 * <p>GENERATED by {@code tools/gen_fish_bounds.py} — do not hand-edit; redraw a sprite and re-run it.
 *
 * <p>The keepnet draws a fish at the size of the cells it occupies, and that is impossible to get right
 * without this: a ray fills its canvas almost corner to corner while an eel is a bar a few pixels tall in
 * the middle of one. Assuming a single set of proportions for all of them made the ray look right and the
 * flounder look tiny, which is the bug this table exists to kill.
 */
public final class FishBounds {
    private static final Map<String, float[]> BOUNDS = new HashMap<>();

    private FishBounds() {}

    private static void put(String species, float w, float h) {
        BOUNDS.put(species, new float[]{w, h});
    }

    /** {width, height} as fractions of the icon, or the whole canvas for anything not a drawn fish. */
    public static float[] of(String species) {
        return BOUNDS.getOrDefault(species, FULL);
    }

    private static final float[] FULL = {1f, 1f};

    static {
        put("anglerfish", 0.969f, 0.492f);
        put("arapaima", 0.945f, 0.223f);
        put("asp", 0.934f, 0.445f);
        put("barracuda", 0.984f, 0.289f);
        put("beluga", 0.945f, 0.246f);
        put("black_marlin", 0.988f, 0.359f);
        put("bleak", 0.957f, 0.418f);
        put("blobfish", 0.945f, 0.441f);
        put("blue_bream", 0.973f, 0.465f);
        put("blue_marlin", 0.961f, 0.344f);
        put("bluefin_tuna", 0.984f, 0.465f);
        put("bluefish", 0.977f, 0.348f);
        put("bluegill", 0.926f, 0.594f);
        put("bream", 0.984f, 0.555f);
        put("bull_shark", 0.945f, 0.387f);
        put("bullseye_snakehead", 0.93f, 0.32f);
        put("burbot", 0.961f, 0.266f);
        put("carp", 0.938f, 0.488f);
        put("carp_koi_asagi", 0.938f, 0.496f);
        put("carp_koi_bekko", 0.938f, 0.48f);
        put("carp_koi_kohaku", 0.938f, 0.5f);
        put("carp_koi_showa_sanke", 0.938f, 0.484f);
        put("carp_koi_tancho_sanke", 0.938f, 0.5f);
        put("catfish", 0.98f, 0.238f);
        put("channel_catfish", 0.965f, 0.312f);
        put("char", 0.977f, 0.324f);
        put("chub", 0.98f, 0.383f);
        put("cod", 0.961f, 0.371f);
        put("common_dace", 0.969f, 0.391f);
        put("conger", 0.941f, 0.148f);
        put("crucian_carp", 0.938f, 0.5f);
        put("eel", 0.98f, 0.141f);
        put("flounder", 0.984f, 0.488f);
        put("frilled_shark", 0.945f, 0.191f);
        put("garfish", 0.93f, 0.141f);
        put("golden_crucian", 0.945f, 0.465f);
        put("golden_dorado", 0.945f, 0.391f);
        put("goliath_grouper", 0.938f, 0.414f);
        put("gorchak", 0.906f, 0.508f);
        put("grass_carp", 0.984f, 0.441f);
        put("grayling", 0.938f, 0.445f);
        put("gudgeon", 0.891f, 0.363f);
        put("halibut", 0.965f, 0.422f);
        put("herring", 0.945f, 0.293f);
        put("ide", 0.973f, 0.438f);
        put("jack_crevalle", 0.945f, 0.449f);
        put("kutum", 0.938f, 0.445f);
        put("largemouth_bass", 0.949f, 0.484f);
        put("lenok", 0.98f, 0.375f);
        put("linear_carp", 0.938f, 0.5f);
        put("loach", 0.953f, 0.293f);
        put("mackerel", 0.957f, 0.309f);
        put("mahi", 0.965f, 0.496f);
        put("mako", 0.969f, 0.434f);
        put("mayan_cichlid", 0.871f, 0.477f);
        put("mirror_carp", 0.938f, 0.5f);
        put("mullet", 0.953f, 0.383f);
        put("naked_carp", 0.938f, 0.5f);
        put("nase", 0.961f, 0.383f);
        put("nelma", 0.953f, 0.379f);
        put("ocean_sunfish", 0.875f, 0.957f);
        put("oscar", 0.941f, 0.613f);
        put("peacock_bass", 0.945f, 0.441f);
        put("perch", 0.953f, 0.398f);
        put("pike", 0.965f, 0.258f);
        put("pink_salmon", 0.961f, 0.402f);
        put("piraiba", 0.945f, 0.289f);
        put("pollock", 0.953f, 0.387f);
        put("rainbow_trout", 0.941f, 0.352f);
        put("ray", 0.863f, 0.742f);
        put("red_piranha", 0.945f, 0.508f);
        put("roach", 0.984f, 0.477f);
        put("rotan", 0.969f, 0.398f);
        put("round_goby", 0.957f, 0.414f);
        put("rudd", 0.953f, 0.477f);
        put("ruffe", 0.953f, 0.551f);
        put("sabrefish", 0.945f, 0.316f);
        put("sailfish", 0.949f, 0.445f);
        put("saithe", 0.973f, 0.305f);
        put("salmon", 0.977f, 0.359f);
        put("sculpin", 0.938f, 0.371f);
        put("seabass", 0.957f, 0.43f);
        put("silver_carp", 0.953f, 0.438f);
        put("smelt", 0.977f, 0.312f);
        put("snook", 0.973f, 0.363f);
        put("sterlet", 0.98f, 0.32f);
        put("striped_bass", 0.969f, 0.43f);
        put("sturgeon", 0.98f, 0.32f);
        put("swordfish", 0.984f, 0.402f);
        put("taimen", 0.961f, 0.316f);
        put("tarpon", 0.977f, 0.383f);
        put("tench", 0.98f, 0.406f);
        put("tiger_shark", 0.949f, 0.375f);
        put("trout", 0.953f, 0.367f);
        put("tubenose_goby", 0.938f, 0.383f);
        put("verkhovka", 0.945f, 0.398f);
        put("vimba", 0.965f, 0.398f);
        put("volga_zander", 0.977f, 0.348f);
        put("wahoo", 0.973f, 0.223f);
        put("whale_shark", 0.969f, 0.379f);
        put("white_bream", 0.961f, 0.465f);
        put("white_eye_bream", 0.949f, 0.512f);
        put("whitefish", 0.984f, 0.406f);
        put("wild_carp", 0.938f, 0.469f);
        put("yellowfin_tuna", 0.965f, 0.414f);
        put("zander", 0.977f, 0.391f);
    }
}
